config/routes.rb
Rails.application.routes.draw do
  resources :candidates do
    member do
      post :vote 
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/candidate.rb
class Candidate < ApplicationRecord
  validates :name, presence: true
  
  has_many :vote_logs
end

app/models/product.rb
class Product < ApplicationRecord
 # belongs_to :store
  
  has_many :ware_houses
  has_many :stores,through: :ware_houses
end

app/models/store.rb
class Store < ApplicationRecord
  belongs_to :user
  #has_many :products
  
   has_many :ware_houses
  has_many :products,through: :ware_houses
end

app/models/user.rb
class User < ApplicationRecord
  has_one :store
end

app/models/vote_log.rb
class VoteLog < ApplicationRecord
  belongs_to :candidate , counter_cache: true
end

app/models/ware_house.rb
class WareHouse < ApplicationRecord
  belongs_to :store
  belongs_to :product
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
  before_action :find_candidate , only:[ :edit , :update, :show, :destroy ,:vote ]
  
   def index
    @candidates=Candidate.all
  end
  
  def new
    @candidate = Candidate.new
  end
  
  def create
    @candidate=Candidate.new(candidate_params)
    
    if @candidate.save
       flash[:notice] ="Candidate was created successfully"
       redirect_to candidates_path
    else
      render "new"
    end  
  end
  
  def edit
  end  
  
  def update
    if @candidate.update(candidate_params)
      redirect_to candidates_path,notice: "Candidate was updated successfully"
    else
      render "edit"
    end  
  end
  
  def destroy
    @candidate.destroy
    redirect_to candidates_path,notice: "Candidate was deleted successfully"
  end  
  
  def show
  end
  
  def vote
     #create(ip_address: request.remote_ip) if @candidate
    @candidate.vote_logs.create(ip_address: request.remote_ip)
    redirect_to candidates_path,notice: "Vote!"
  end
  
  private
  def candidate_params
    params[:candidate].permit(:name,:party,:age,:comment)
  end
  
  def find_candidate
    @candidate=Candidate.find_by(id: params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/candiates_helper.rb
module CandiatesHelper
  def show_your_age(age)
    if age >=18
      "YES"
    else
      "NO"
    end
  end
  
  #顏色分票數
  def vote_formal(candidate)
    count=candidate.vote_logs.size
    if  count>5
      "<b style=color:blue>#{count}</b>".html_safe 
    else
     "<b style=color:red>#{count}</b>".html_safe 
    end
  end
end

app/views/candidates/_form.html.erb
<%= simple_form_for (candidate) do |f| %>
    name: <%= f.input :name %> <br />
    party: <%= f.input :party %><br/>
    age: <%= f.input :age %><br/>
    comment: <%= f.input :comment %><br/>
  
    <%= f.submit %>  
<% end %>

app/views/candidates/edit.html.erb
<h1> Edit Candidate</h1>

<%= render "form", candidate: @candidate%>

app/views/candidates/index.html.erb
<h1>Candidate List</h1>
 
<table class="table">
  <thead>
    <tr>
      <td>count</td>
      <td>name</td>
      <td>party</td>
      <td>age</td>
      <td>comment</td>
      <td></td>
    </tr>
  </thead>
  <tbody>
    <% @candidates.each do |candidate| %>
      <tr>
        <td>
          <% candidate.vote_logs.size %>
          <%= vote_formal(candidate) %>
          <%= link_to "Vote!", vote_candidate_path(candidate) ,method:"post", class:"btn btn-primary btn-xs" %>
        </td>
        <td><%= link_to candidate.name ,  candidate_path(candidate) %></td>
        <td><%= candidate.party %></td>
        <td><%= candidate.age %></td>
        <td><%= candidate.comment %></td>
        <td><%= link_to "edit" , edit_candidate_path(candidate) , class:"btn btn-success" %></td>
        <td><%= link_to "delete" , candidate_path(candidate) ,method:"delete",data:{confirm:"Are you sure?"} ,class:"btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
  <tfoot>
  </tfoot>
</table>
 
<%= link_to "add candidate", new_candidate_path , class:"btn btn-info" %> <br/>

app/views/candidates/new.html.erb
<h1>add candidate</h1>

<%= render "form" , candidate: @candidate %>

app/views/candidates/show.html.erb
<h1> Show Candidate</h1>

Name:<%= @candidate.name %> <br/>
Party:<%= @candidate.party %> <br/>
Age:<%= @candidate.age %> <br/>
Comment:<%= @candidate.comment %> <br/>

<%= show_your_age(@candidate.age) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyVote</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <% if flash[:notice] %>
      <div class="alert alert-info" role="alert"><%= flash[:notice] %></div>
      <% end %>
      <%= yield %>  
    </div>
  </body>
</html>